//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coursse
    {
        public Coursse()
        {
            this.Announcements = new HashSet<Announcement>();
            this.Assignments = new HashSet<Assignment>();
            this.ExamSchedules = new HashSet<ExamSchedule>();
            this.Reports = new HashSet<Report>();
            this.Routines = new HashSet<Routine>();
            this.Schedules = new HashSet<Schedule>();
            this.Sessions = new HashSet<Session>();
            this.StudentCourses = new HashSet<StudentCourse>();
            this.TeacherCourses = new HashSet<TeacherCourse>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte Cradit { get; set; }
        public string Description { get; set; }
        public int DepertmentId { get; set; }
    
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual Depertment Depertment { get; set; }
        public virtual ICollection<ExamSchedule> ExamSchedules { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<Routine> Routines { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
        public virtual ICollection<TeacherCourse> TeacherCourses { get; set; }
    }
}
