//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depertment
    {
        public Depertment()
        {
            this.Coursses = new HashSet<Coursse>();
            this.StudentDepertments = new HashSet<StudentDepertment>();
            this.TeacherDepertments = new HashSet<TeacherDepertment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AddressId { get; set; }
        public int InstituteId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Coursse> Coursses { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual ICollection<StudentDepertment> StudentDepertments { get; set; }
        public virtual ICollection<TeacherDepertment> TeacherDepertments { get; set; }
    }
}
