//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institute
    {
        public Institute()
        {
            this.Depertments = new HashSet<Depertment>();
            this.UserInstitutes = new HashSet<UserInstitute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public string WebSite { get; set; }
        public System.DateTime EstDate { get; set; }
        public int ContactId { get; set; }
        public byte NumberOfDepertment { get; set; }
        public Nullable<int> PresentAddressId { get; set; }
        public Nullable<int> AddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Depertment> Depertments { get; set; }
        public virtual PresentAddress PresentAddress { get; set; }
        public virtual ICollection<UserInstitute> UserInstitutes { get; set; }
    }
}
