//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentAddress
    {
        public PresentAddress()
        {
            this.Institutes = new HashSet<Institute>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int CountryID { get; set; }
        public int ZipCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Institute> Institutes { get; set; }
        public virtual Zip Zip { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
