//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quise
    {
        public Quise()
        {
            this.SessionQuises = new HashSet<SessionQuise>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual ICollection<SessionQuise> SessionQuises { get; set; }
    }
}
