//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
       

        public Session()
        {
            this.SessionQuises = new HashSet<SessionQuise>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Video { get; set; }
        public int MaterialsId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int QuiseId { get; set; }
        public int CourseId { get; set; }
        public int Coursse_Id { get; set; }
        internal int Material_id { get; set; }

        public virtual Coursse Coursse { get; set; }
        public virtual Material Material { get; set; }
        public virtual ICollection<SessionQuise> SessionQuises { get; set; }
    }
}
