//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionQuise
    {
        public int Id { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> QuiseId { get; set; }
    
        public virtual Quise Quise { get; set; }
        public virtual Session Session { get; set; }
    }
}
