//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentCourses = new HashSet<StudentCourse>();
            this.StudentDepertments = new HashSet<StudentDepertment>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Started { get; set; }
        public Nullable<System.DateTime> Graduated { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
        public virtual ICollection<StudentDepertment> StudentDepertments { get; set; }
    }
}
