//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDQWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.TeacherCourses = new HashSet<TeacherCourse>();
            this.TeacherDepertments = new HashSet<TeacherDepertment>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Joined { get; set; }
        public Nullable<System.DateTime> Resign { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<TeacherCourse> TeacherCourses { get; set; }
        public virtual ICollection<TeacherDepertment> TeacherDepertments { get; set; }
    }
}
